# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: 2.7.1

      - name: Bundle Install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup database
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:seed
        env:
          RAILS_ENV: test

      - name: Run Tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec spec/models --color --tty --format progress
